### ISSUE TITLE
size buttons

### ISSUE THREAD

**Issue by jjimenez0611** [xojan/CustomNumberPad#1]
Hi

Is some way to resize the buttons?

**Comment by joan-domingo** [comment]
What do you mean exactly? you want to resize each button individually?

**Comment by jjimenez0611** [comment]
Hi 

maybe not individually, in general, for example if I want to have a margin between each button to make the button more small!

Best Regards

**Comment by joan-domingo** [comment]
Hi Jose,
at the moment is not possible, but I will take a look and maybe it is easy to do.

**Comment by joan-domingo** [comment]
Hi again,

I updated the libary and I hope it can help you. Have a look please.
Remember to update the dependency: 
```
compile 'cat.xojan:numpad:1.1.0'
```
and use the new attributes:
```
numpad:verticalSeparatorMargin="12dp"
numpad:horizontalSeparatorMargin="12dp"
```

Let me know.

**Comment by jjimenez0611** [comment]
Hi

Excellent, thank so much! This is very useful.. 👍

**Comment by joan-domingo** [comment]
happy to help 😃
